language: minimal

git:
  depth: 1

env:
  global:
    - GRAVIS_REPOSITORY="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS_HOME="$HOME/gravis"
    - JDK="adopt@1.11"

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - echo INSTALL
  - travis_retry git clone --depth 1 $GRAVIS_REPOSITORY $GRAVIS_HOME
  - . $GRAVIS_HOME/install-jdk

before_cache:
  - echo BEFORE CACHE
  - . $GRAVIS_HOME/clean-gradle-cache

before_script:
  - echo BEFORE SCRIPT
  - chmod u+x gradlew
  - chmod u+x src/test/resources/*/bin/*

script:
  - echo SCRIPT
  - ./gradlew :build --console=plain

matrix:
  include:
    - os: linux
      dist: bionic
      git:
        depth: false
      addons:
        sonarcloud:
          organization: siouan
          token:
            secure: "I7ymzi1DWGQ3JZqmWRYyCb5UuNRhH0ieSSZlspzPsnoYxFJNhxYhkL2CaijPbhR06Acnvjn0txKeJrvTNxG4dq4efe5jCMHqzIjLJ7AGRVppBC1t4DszoZ0ovrXldsZ4MjILEwFZdUrPiAynUYgQR0z/cN5LBD0wn+dwjbmp2GvJWg/r1IlodShI2f5eFO3hy8g/4361xGkv3ROVvGbL7YmaSNJ80sJEcAGBKi1NDi91bZ3azUoQ2e7QVLTvWhfpB6HBm0lHH4oe2Ie/tJAFBiuf94QDS0C38pGI8YqnIig5uvoerZLxc96EoxyJ555OT8dcxYf1thSaW1Mo2HerOvmtQtt7+58l0SDX51VCwv0t7+Whh84DLKiU28PntGV8YXjfyuTsbxiCTpyh0CJzOocVH/XaMU5MO58spITo4X9xK9NYzvbKmKVvGYiQw0CUsJ5XYkhjqrGq5aZJSVrUFX72vvV31zw/KCwnqxO5lkZc+SOoynIHfn/s8l1dG40rLEs5/zXG4GXMsBe3T2S7ieZGy2TaJMQyiyg/0Yx8VvmV/ex0oxKRpe4a+/CyhhxDjDSDukSTdVY+gCq97ZVdafNi7ltIqndTUErOwt8BRsOMUFWzuwNq6UZuDjAQ4gHhKVO0827AH7/pD8hMBlBGsT1hp4njT/fwUPET0OoWz5M="
      cache:
        directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.sonar/cache
      before_install:
        - echo BEFORE_INSTALL
        # Travis - Ubuntu Bionic: Yarn is already installed
        - sudo rm -f /usr/local/bin/yarn
      script:
        - echo SCRIPT
        - ./gradlew test --tests org.siouan.frontendgradleplugin.infrastructure.gradle.NpmTaskTypeWithExitCodeFuncTest
#        - ./gradlew build jacocoTestReport --console=plain
#        - sonar-scanner

#    - os: osx
#      osx_image: xcode9.4
#      before_install:
#        - echo BEFORE_INSTALL
#        # Travis - Mac OS: Node.js is already installed plus other libraries
#        - brew uninstall node
#        - rm -fr $NVM_DIR
#        - rm -f /usr/local/bin/npm /usr/local/bin/npx

#    - os: windows
#      env:
#        # Travis - Windows: disable Defender that slows the build and caching.
#        - NO_WIN_DEFENDER=$(curl "${GRAVIS_HOME}/.disable-windows-defender.sh" --output .no-defender.sh && . .no-defender.sh)
