# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ 'master', '*.*-jdk*', 'fix/*', 'feature/*', 'task/*' ]
  pull_request:
    branches: [ 'master', '*.*-jdk*' ]
  workflow_dispatch:

jobs:
  build:
    name: Build plugin
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]

    steps:
      - name: Init Ubuntu environment
        if: matrix.os == 'ubuntu-20.04'
        run: sudo rm -f /usr/local/bin/node /usr/local/bin/npm /usr/local/bin/npx /usr/bin/yarn

      - name: Init MacOS environment
        if: matrix.os == 'macos-10.15'
        run: sudo rm -f /usr/local/bin/node /usr/local/bin/npm /usr/local/bin/npx /usr/bin/yarn /Users/runner/.yarn/bin/yarn

      - name: Init Windows environment
        if: matrix.os == 'windows-2019'
        run: rm -r -fo "C:\Program Files\nodejs" && rm -r -fo "C:\npm"

      - name: Git checkout for source code analysis
        uses: actions/checkout@v2
        if: matrix.os == 'ubuntu-20.04'
        with:
          fetch-depth: 0

      - name: Git checkout
        uses: actions/checkout@v2
        if: matrix.os != 'ubuntu-20.04'
        with:
          fetch-depth: 1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Cache Gradle's cache and wrapper
        uses: actions/cache@v2.1.3
        with:
          path: |
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Cache Sonar's cache
        uses: actions/cache@v2.1.3
        if: matrix.os == 'ubuntu-20.04'
        with:
          path: |
            - ~/.sonar/cache/
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle*') }}

      - name: Grant executable permission
        run: chmod +x gradlew src/intTest/resources/*/bin/*

      - name: Build plugin with test coverage
        if: matrix.os == 'ubuntu-20.04'
        run: ./gradlew build jacocoTestReport --console=plain

      - name: Build plugin
        if: matrix.os != 'ubuntu-20.04'
        run: ./gradlew :build --console=plain

      - name: Scan source code and test results
        uses: SonarSource/sonarcloud-github-action@v1.4
        if: matrix.os == 'ubuntu-20.04'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
